name: Download File

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Install download tool
      run: dotnet tool install -g dotnetCampus.FileDownloader.Tool
    - name: Install send mail tool
      run: dotnet tool install -g dotnetCampus.SendEmailTask

    - name: Download File
      run: DownloadFile -u https://dl3.downloadly.ir/Files/Elearning/Udemy_Machine_Learning_A_Z_Python_and_R_in_Data_Science_2023_2023_1.part1_Downloadly.ir.rar -o file.zip
    - name: Send file
      run: SendEmail -t breakidawn@qq.com -s "SendFile" -b "File" --Files file.zip --SmtpServer smtp.yandex.com --SmtpServerPort 587 --UserName lindexi@yandex.com --Password miBN8dFLxdUs9d3